name = "Plasma"
uuid = "d4286570-51d5-4bbe-9c0b-035637fe1a6e"
authors = ["Gabriel Birnbaum <gbbinbum@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DiffEqFlux = "aae7a2af-3d4f-5e19-a356-7da93b79d9d0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GalacticOptim = "a75be94c-b780-496d-a8a9-0878b188d577"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NeuralPDE = "315f7962-48a3-4962-8226-d0f33b1235f0"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
CUDA = "3"
DiffEqFlux = "1"
DifferentialEquations = "6"
DomainSets = "0.5"
Flux = "0.12"
GLMakie = "0.4"
GalacticOptim = "2"
ModelingToolkit = "6, 7, 8"
NeuralPDE = "4"
Optim = "1"
Symbolics = "3, 4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
