name = "Plasma"
uuid = "d4286570-51d5-4bbe-9c0b-035637fe1a6e"
authors = ["Gabriel Birnbaum <gbbinbum@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DiffEqFlux = "aae7a2af-3d4f-5e19-a356-7da93b79d9d0"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GalacticOptim = "a75be94c-b780-496d-a8a9-0878b188d577"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Flux = "0.12"
GalacticOptim = "2"
DiffEqFlux = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
